### ISSUE TITLE
Compilation Error in 'obs_multi_auto_mean', 'mono_dim', 'obs_multi'

### ISSUE THREAD

**Issue by navil2000** [resibots/limbo#331] opened 2023-10-17 09:55 UTC
**Summary:**

I'm encountering a compilation error when building Limbo. Specifically, I'm getting a failure in the compilation tasks for 'obs_multi_auto_mean', 'mono_dim', and 'obs_multi' with an exit status of 1. This issue is preventing me from successfully building Limbo.

**Details:**

- **Operating System:** Ubuntu 22.04.1 LTS
- **Python Version:** Python 3.10.12
- **Steps to Reproduce:**

    1. Clone the Limbo repository.
    2. Install the necessary dependencies (list them).
    3. Configure `./waf configure`.
    3. Run the compilation with `./waf build`.
    
 **Error Messages:** 
 
 Build failed
 -> task in 'opt' failed with exit status 1: 
	{task 139827118384048: cxx opt.cpp -> opt.cpp.4.o}
['/usr/bin/g++', '-Wall', '-std ...]
 -> task in 'gp' failed with exit status 1: 
	{task 139827118383824: cxx gp.cpp -> gp.cpp.3.o}
['/usr/bin/g++', '-Wall', '-std...]
-> task in 'basic_example' failed with exit status 1: 
	{task 139827118383376: cxx basic_example.cpp -> basic_example.cpp.1.o}
['/usr/bin/g++', '-Wall', '-std...]
 -> task in 'mono_dim' failed with exit status 1: 
	{task 139827118381584: cxx mono_dim.cpp -> mono_dim.cpp.1.o}
['/usr/bin/g++', '-Wall', '-std...]
-> task in 'obs_multi_auto_mean' failed with exit status 1: 
	{task 139827118383152: cxx obs_multi_auto_mean.cpp -> obs_multi_auto_mean.cpp.3.o}
['/usr/bin/g++', '-Wall', '-std...]
 -> task in 'statistics' failed with exit status 1: 
	{task 139827118383600: cxx statistics.cpp -> statistics.cpp.2.o}
['/usr/bin/g++', '-Wall', '-std...]

**Comment by costashatz** [comment] 2023-10-17 09:57
Thanks for using our library.

Can you give us the full output? We cannot really understand anything from what you copy/pasted.

**Comment by navil2000** [comment] 2023-10-17 10:04
Thank you all for the project, it's very good, and I hope to be able to use the library in future projects.

I'm sorry, I thought that with that part of the error would be enough... Here is the complete output (+screenshots):

./waf build -v
YELLOW: Could not import plot_bo_benchmarks! Will not plot anything! 
build dir not created (it probably already exists, this is fine)
Waf: Entering directory `/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build'
[ 8/22] Linking build/src/liblimbo.a
11:43:05 runner ['/usr/bin/ar', 'rcs', 'src/liblimbo.a', 'src/ehvi/ehvi_calculations.cc.1.o', 'src/ehvi/ehvi_montecarlo.cc.1.o', 'src/ehvi/ehvi_sliceupdate.cc.1.o', 'src/ehvi/ehvi_hvol.cc.1.o', 'src/ehvi/ehvi_multi.cc.1.o', 'src/ehvi/helper.cc.1.o', 'src/hv/hypervol.c.1.o']
[ 9/22] Compiling src/examples/mono_dim.cpp
11:43:05 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/examples', '-I../src/examples', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/examples/mono_dim.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/examples/mono_dim.cpp.1.o']
[10/22] Compiling src/examples/obs_multi.cpp
11:43:05 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/examples', '-I../src/examples', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/examples/obs_multi.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/examples/obs_multi.cpp.2.o']
[11/22] Compiling src/examples/obs_multi_auto_mean.cpp
11:43:05 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/examples', '-I../src/examples', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/examples/obs_multi_auto_mean.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/examples/obs_multi_auto_mean.cpp.3.o']
[12/22] Compiling src/tutorials/basic_example.cpp
11:43:05 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/basic_example.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/basic_example.cpp.1.o']
[13/22] Compiling src/tutorials/statistics.cpp
11:43:05 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/statistics.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/statistics.cpp.2.o']
[14/22] Compiling src/tutorials/gp.cpp
11:43:05 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/gp.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/gp.cpp.3.o']
[15/22] Compiling src/tutorials/opt.cpp
11:43:05 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/opt.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/opt.cpp.4.o']
In file included from ../src/tutorials/opt.cpp:46:
../src/limbo/opt.hpp:57:2: warning: #warning NO CMA-ES [-Wcpp]
   57 | #warning NO CMA-ES
      |  ^~~~~~~
In file included from ../src/limbo/opt/parallel_repeater.hpp:55,
                 from ../src/limbo/opt.hpp:66,
                 from ../src/tutorials/opt.cpp:46:
../src/limbo/tools/parallel.hpp:61:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
   61 | #include <tbb/task_scheduler_init.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../src/limbo/tools.hpp:52,
                 from ../src/limbo/model/gp.hpp:67,
                 from ../src/limbo/bayes_opt/bo_base.hpp:70,
                 from ../src/limbo/bayes_opt/boptimizer.hpp:57,
                 from ../src/examples/obs_multi.cpp:47:
../src/limbo/tools/parallel.hpp:61:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
   61 | #include <tbb/task_scheduler_init.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../src/limbo/tools.hpp:52,
                 from ../src/limbo/model/gp.hpp:67,
                 from ../src/tutorials/gp.cpp:50:
../src/limbo/tools/parallel.hpp:61:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
   61 | #include <tbb/task_scheduler_init.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../src/limbo/tools.hpp:52,
                 from ../src/limbo/model/gp.hpp:67,
                 from ../src/limbo/bayes_opt/bo_base.hpp:70,
                 from ../src/limbo/bayes_opt/boptimizer.hpp:57,
                 from ../src/tutorials/basic_example.cpp:51:
../src/limbo/tools/parallel.hpp:61:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
   61 | #include <tbb/task_scheduler_init.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../src/limbo/tools.hpp:52,
                 from ../src/limbo/model/gp.hpp:67,
                 from ../src/limbo/bayes_opt/bo_base.hpp:70,
                 from ../src/limbo/bayes_opt/boptimizer.hpp:57,
                 from ../src/examples/mono_dim.cpp:47:
../src/limbo/tools/parallel.hpp:61:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
   61 | #include <tbb/task_scheduler_init.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../src/limbo/tools.hpp:52,
                 from ../src/limbo/model/gp.hpp:67,
                 from ../src/limbo/bayes_opt/bo_base.hpp:70,
                 from ../src/limbo/bayes_opt/boptimizer.hpp:57,
                 from ../src/examples/obs_multi_auto_mean.cpp:46:
../src/limbo/tools/parallel.hpp:61:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
   61 | #include <tbb/task_scheduler_init.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../src/limbo/tools.hpp:52,
                 from ../src/limbo/model/gp.hpp:67,
                 from ../src/limbo/bayes_opt/bo_base.hpp:70,
                 from ../src/limbo/bayes_opt/boptimizer.hpp:57,
                 from ../src/limbo/bayes_opt.hpp:49,
                 from ../src/limbo/limbo.hpp:50,
                 from ../src/tutorials/statistics.cpp:49:
../src/limbo/tools/parallel.hpp:61:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
   61 | #include <tbb/task_scheduler_init.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Waf: Leaving directory `/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build'
Build failed
 -> task in 'opt' failed with exit status 1: 
	{task 139827118384048: cxx opt.cpp -> opt.cpp.4.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/opt.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/opt.cpp.4.o']
 -> task in 'obs_multi' failed with exit status 1: 
	{task 139827118382928: cxx obs_multi.cpp -> obs_multi.cpp.2.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/examples', '-I../src/examples', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/examples/obs_multi.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/examples/obs_multi.cpp.2.o']
 -> task in 'gp' failed with exit status 1: 
	{task 139827118383824: cxx gp.cpp -> gp.cpp.3.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/gp.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/gp.cpp.3.o']
 -> task in 'basic_example' failed with exit status 1: 
	{task 139827118383376: cxx basic_example.cpp -> basic_example.cpp.1.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/basic_example.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/basic_example.cpp.1.o']
 -> task in 'mono_dim' failed with exit status 1: 
	{task 139827118381584: cxx mono_dim.cpp -> mono_dim.cpp.1.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/examples', '-I../src/examples', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/examples/mono_dim.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/examples/mono_dim.cpp.1.o']
 -> task in 'obs_multi_auto_mean' failed with exit status 1: 
	{task 139827118383152: cxx obs_multi_auto_mean.cpp -> obs_multi_auto_mean.cpp.3.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/examples', '-I../src/examples', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/examples/obs_multi_auto_mean.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/examples/obs_multi_auto_mean.cpp.3.o']
 -> task in 'statistics' failed with exit status 1: 
	{task 139827118383600: cxx statistics.cpp -> statistics.cpp.2.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-O3', '-g', '-march=native', '-Isrc/tutorials', '-I../src/tutorials', '-Isrc', '-I../src', '-I.', '-I..', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include', '-DUSE_TBB', '-DUSE_NLOPT', '../src/tutorials/statistics.cpp', '-c', '-o/home/robesafe/shared_home/TFM_Cost_Function_Opt/TFM-Tests/Limbo_cpp/limbo/build/src/tutorials/statistics.cpp.2.o']

![image](https://github.com/resibots/limbo/assets/57594103/da3ef328-847a-432b-b5e5-a02ae32dd305)

![image](https://github.com/resibots/limbo/assets/57594103/7d348e3b-7ebe-4dea-829e-9fc9e50cf2ff)

![image](https://github.com/resibots/limbo/assets/57594103/8d3e790f-ecf6-4595-b087-399d20d57210)

**Comment by costashatz** [comment] 2023-10-17 10:22
Thanks!

This is a duplicate of https://github.com/resibots/limbo/issues/315. I just pushed a [commit](https://github.com/resibots/limbo/commit/0246cf190fac6c7368a2a1e57e4a7b463fde7901) to master that should fix this. Let me know if it does so that I can close the other issue as well.

Btw, I see that you haven't installed libcmaes (or nlopt). I advise you to do so, otherwise limbo would be poorly performing.

**Comment by navil2000** [comment] 2023-10-17 10:51
Thank you! Now it works!
I've had some difficulties installing nlopt, but I've managed to do it. Thank you very much!
I believe this issue can be closed, sorry for the inconvenience :)

**Comment by costashatz** [comment] 2023-10-17 10:52
Great to hear that everything is good!

**Closed by costashatz** 2023-10-17 10:52 UTC
